appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RbBf+nb9emZFu4OhgEipiN+x0fRJM+nCdUTaLd2UWk8DZd+X55e2+9+urcdW0zuivUutqRxlZ2+Snwkx7sWTwE5e7x58Ng7JcNINSBsRAXSduiM0TEhVmE9C0mICi8kB8qsuTUxfyg2iudgdaZRLDIeuRe/CNQdhHyJfvi1sRcE2cWOUV/kLLLk9jiG24r5lUvX4+R8NxdWJbRldscJjSFt8KcdNVZvlZe//DFhT8yb0rF/hqZmSNiOrv0KyRI3uxPq0UYZsBZ8paUS+nUgFka+yl94nVKeYCSt7H0b0wiBISDQcWXkA3upE9D/3qqT4GKrGWzSL04yHPM5Ezxl7+eXrUfdBuM2SmM0vVI/AeBRy6YfGlLnpyyc0IETlakdaeyHTWUWM8dBPuzvW8xww0CIHzdlkiAqu9QMbm3XIj9w2qrBS1j4GUUgkFtRcJwxPJzcRxrT1SciDXXbCkwbUCk88fnPMyGUj6bYO1/e3mjtrUc8mLCzcu+FJAtkVqaRgddKNmA8XUeSnBC7YCvxStFbwPlgOXRBhfnJ5RZ/Oq/mBwWPeAesi9tibmM0LhuRpRwp/RYSedhKmNwlHjWtH9vL2VxF6mSjLaUa6DgCVKzsxpTfqC4ZLVv965zxEc8wmo+IUY1ftJxt2d/Ai0fOC5pc+QfaflJRbLf0FHN+kzW8=}
